
apiVersion: v1

kind: Service 

metadata:
  name: visits-service
  labels:
    app: visits-service-svc-label

spec:
  ports:
  - port: 9999
    name: http

  selector:
    app: visits-service-v1

  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: visits-service-deployment-v1
  labels:
    app: visits-service-dep-label

spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: visits-service-v1

  template: # template for the pods
    metadata:
      labels:
        app: visits-service-v1

    spec:
      containers:
      - name: visits-service-ver1
        image: saurabh2204/online-appointment-visits-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9898